{
 "title": "DB status_report_lt",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))\r\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Session count by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (host, pod) (kqp_SessionActors_Active{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "{{host}}{{pod}}"
    }
   ]
  },
  {
   "title": "Session count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "sum(kqp_SessionActors_Active{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "DbDataSize (gb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbDataBytes_{database=\"$database\",container=\"ydb-dynamic\"})/1073741824",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Aborted transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(kqp_Transactions_Aborted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "TxTotalTimes percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  { "title": "Useful", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Cache hit pages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheHitPages{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "pages"
    }
   ]
  },
  {
   "title": "TxTotalTimes (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))\r\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache miss pages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheMissPages{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "pages"
    }
   ]
  },
  {
   "title": "RowRead rows per request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_DataShard_SelectRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RowRead rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "max TxCompleteLag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "DbUniqueRowsTotal",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbUniqueRowsTotal_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "Memory consumed by tablets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_ConsumedMemory_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "DbRowsTotal | DbRowsErase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbRowsTotal_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "rows total"
    },
    {
     "expr": "sum(tablets_SUM_DbRowsErase_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "rows erase"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum(ydb_resources_storage_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "used bytes"
      },
      {
       "expr": "sum(ydb_resources_storage_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "limit bytes"
      }
     ]
    },
    {
     "title": "RowRead bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_EngineHostRowReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "CPU by thread pool (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum by (execpool) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{execpool}}"
      }
     ]
    },
    {
     "title": "DataShard TX Count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+Completed\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)Completed\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "ExecPrepared latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_ExecPreparedLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))\r\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "UploadRows bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_UploadRowsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "CPU in user pool by host (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "DataShard ExecuteCPUTime (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_ExecuteCPUTime\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_ExecuteCPUTime\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "RangeRead rows",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "ReadColumns bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadColumnsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "RSS size by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "sum by (host, pod) (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "---",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 50 },
     "targets": [
      {}
     ]
    },
    {
     "title": "RangeRead bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Coordinator cpu usage (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 55 },
     "targets": [
      {
       "expr": "sum(rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_COORDINATOR_ACTOR\"}[$__rate_interval]))",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum(ydb_table_query_compilation_cache_size_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "DbUniqueDataBytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "sum(tablets_SUM_DbUniqueDataBytes_{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "RangeRead rows per request",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_RangeReadRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ReadReplicas sync latency (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 60 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_FollowerSyncLatency_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "---",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 60 },
     "targets": [
      {}
     ]
    },
    {
     "title": "YQL issues: unavailable",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 60 },
     "targets": [
      {
       "expr": "sum(rate(kqp_Issues_YQL:KIKIMR_TEMPORARILY_UNAVAILABLE{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "DataShard tablets count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(utils_ActorsAliveByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_DATASHARD_ACTOR\"})",
       "legendFormat": "tablets"
      }
     ]
    },
    {
     "title": "DSProxy PutUserData latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 65 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutUserData\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "YQL issues",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"kqp_Issues_YQL:.+\"}, \"name_label\", \"$1\", \"__name__\", \"kqp_Issues_YQL:(.+)\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "Tasks in ResourceBroker queues",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 65 },
     "targets": [
      {
       "expr": "sum by (queue) (tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "UploadRows rows",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_UploadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "DSProxy GetDiscover latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetDiscover\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "gRpc StreamReadTable",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum(grpc_infly{database=\"$database\",container=\"ydb-dynamic\",request=\"StreamReadTable\"})",
       "legendFormat": "infly"
      }
     ]
    },
    {
     "title": "DataShard ImmediateTxInFly",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 70 },
     "targets": [
      {
       "expr": "sum(tablets_SUM_DataShard_ImmediateTxInFly_{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "transactions"
      }
     ]
    },
    {
     "title": "ReadColumns rows",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadColumnsRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "DSProxy GetAsync latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 75 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetAsync\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Shards by cpu usage (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum by (le) (tablets_HIST_ConsumedCPU__bucket{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "DSProxy PutAsync latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 75 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutAsync\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Interconnect connected",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "sum(interconnect_Connected{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "Split / Merge partitions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 80 },
     "targets": [
      {
       "expr": "sum(rate(tablets_SchemeShard_FinishedOps_SplitTablePartition{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "splits"
      },
      {
       "expr": "sum(rate(tablets_SchemeShard_FinishedOps_MergeTablePartition{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "merges"
      }
     ]
    },
    {
     "title": "Mediator cpu usage (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 80 },
     "targets": [
      {
       "expr": "sum(rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_MEDIATOR_ACTOR\"}[$__rate_interval]))",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Cache hit bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 80 },
     "targets": [
      {
       "expr": "sum(rate(tablets_CacheHitBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Cache miss bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(rate(tablets_CacheMissBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "DSProxy GetFast latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 85 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetFast\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "DSProxy PutTabletLog latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutTabletLog\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}