{
 "title": "jmeter-dashboard-victoriametrics",
 "description": "Dashboard for Jmeter using Backend listener and VictoriaMetrics.",
 "tags": [ "load_test" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "data_source", "query": "prometheus" },
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "transaction",
    "label": "transaction",
    "query": {
     "query": "label_values(jmeter_count{application=\"$application\",transaction!=\"all\"},transaction)"
    }
   },
   { "name": "UID", "query": "${VAR_UID}" },
   { "name": "dashboardName", "query": "${VAR_DASHBOARDNAME}" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Среднее число метрики за выбранный период",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Среднее рпс",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Общий % ошибок",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}) / \r\n(sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}) + sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}))\r\n* 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Общее количество ошибок",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Общее количество запросов",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}) + sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jmeter_pct99.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Среднее время ответа 95 Pct",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_sb{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_rb{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Now Active Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmeter_maxAT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  { "title": "Main metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Активные потоки",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Threads",
     "expr": "jmeter_maxAT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "RPS",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "RPS",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Время выполнения успешных запросов (95thpct)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "% Error",
   "type": "timeseries",
   "description": "Процент неуспешных запросов в секунду, график урезан до 10 %",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}) \r\n* 100 \r\n/\r\n(sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}) + sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pie - Error Response Code",
   "type": "piechart",
   "description": "Пирог с процентом ошибок по кодам",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode!~\"^$\"}) by (responseCode)",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "% Error",
   "type": "timeseries",
   "description": "Процент неуспешных запросов в секунду",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}) \r\n* 100 \r\n/\r\n(sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}) + sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}))",
     "legendFormat": "${transaction}"
    }
   ]
  },
  {
   "title": "Error Info",
   "type": "table",
   "description": "Таблица с краткой информацией об ошибках",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",responseCode!~\"^$\"}",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "responseMessage" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Время выполнения неуспешных запросов (95thpct)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Failed",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Count Error in 5 sec - by Response Message",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов по кодам за 5 секунд",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseMessage!~\"^$\"}) by (responseMessage)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{responseCode}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5",
     "legendFormat": "Pass"
    },
    {
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"} / 5",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5) + sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"} / 5)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "% OK / KO",
   "type": "timeseries",
   "description": "Процент успешных и неуспешных запросов в секунду",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}) * 100 / sum (jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"})",
     "legendFormat": "OK"
    },
    {
     "expr": "sum (jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}) * 100 / sum (jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"})",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Count Error in 5 sec",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов по кодам ответа",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode!~\"^$\"}) by (responseCode)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{responseCode}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode!~\"^$\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "All",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Table",
     "type": "table",
     "description": "Таблица со статистикой запросов / транзакций",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jmeter_count{application=\"$application\",statut=\"ok\",transaction!=\"all\"}",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "passReq" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_count{application=\"$application\",statut=\"ko\",transaction!=\"all\"}",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "failReq" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_pct90.0{application=\"$application\",transaction!=\"all\"}",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "resTime99" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_pct95.0{application=\"$application\",transaction!=\"all\"}",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "resTime95" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_pct99.0{application=\"$application\",transaction!=\"all\"}",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "resTime99" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_count{application=\"$application\",transaction!=\"all\"} / 5",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 5" ], "type": "math" },
         { "params": [ "rpsAvg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "expr": "jmeter_count{application=\"$application\",transaction!=\"all\"} / 5",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 5" ], "type": "math" },
         { "params": [ "rpsMax" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "History Test",
     "type": "table",
     "description": "Таблица запущенных / завершенных тестов за 30 дней",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 82 },
     "targets": [
      {
       "expr": "jmeter_events{event=\"start\"}",
       "groupBy": [
        { "params": [ "tags" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "events",
       "select": [
        [
         { "params": [ "text" ], "type": "field" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* started/" }
       ]
      },
      {
       "expr": "jmeter_events{event=\"end\"}",
       "groupBy": [
        { "params": [ "tags" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "legendFormat": "__auto",
       "measurement": "events",
       "select": [
        [
         { "params": [ "text" ], "type": "field" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* ended/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Bytes",
     "type": "timeseries",
     "description": "Полученные байты",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "expr": "jmeter_rb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{transaction}}",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "alias": "all",
       "expr": "sum(jmeter_rb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5)",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "all",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "timeseries",
     "description": "Отправленные байты",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "expr": "jmeter_sb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{transaction}}",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "alias": "all",
       "expr": "sum(jmeter_sb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5)",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "all",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Unused",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS - 4xx",
     "type": "timeseries",
     "description": "Кол-во запросов в секунду с кодом ответа 4xx",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"4..\"} / 5",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{transaction}}",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      },
      {
       "alias": "all",
       "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"4..\"} / 5)",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "all",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" }
       ]
      }
     ]
    },
    {
     "title": "RPS - 5xx",
     "type": "timeseries",
     "description": "Кол-во запросов в секунду с кодом ответа 5xx",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 383 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"5..\"} / 5",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{transaction}}",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      },
      {
       "alias": "all",
       "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"5..\"} / 5)",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "all",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" }
       ]
      }
     ]
    },
    {
     "title": "Wait journals",
     "type": "timeseries",
     "description": "Количество записей в журнале со статусом WAIT",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "expr": "jmeter_pct90.0{application=\"$application\",transaction=~\"wait_count_metric\",statut=\"ok\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{transaction}}",
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}