{
 "title": "jmeter-dashboard-victoriametrics",
 "description": "Dashboard for Jmeter using Backend listener and VictoriaMetrics.",
 "tags": [ "load_test" ],
 "time": { "from": "2025-09-12T16:21:29.220Z", "to": "2025-09-12T16:31:14.544Z" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "data_source", "query": "prometheus" },
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "transaction",
    "label": "transaction",
    "query": {
     "query": "label_values(jmeter_count{application=\"$application\",transaction!=\"all\"},transaction)"
    }
   },
   { "name": "UID", "query": "${VAR_UID}" },
   { "name": "dashboardName", "query": "${VAR_DASHBOARDNAME}" }
  ]
 },
 "panels": [
  { "title": "Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "description": "Активные потоки",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Threads",
     "expr": "jmeter_maxAT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "RPS",
     "expr": "jmeter_count{application=\"$application\",transaction=\"all\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "RPS",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  {
   "title": "Response Time - Pass (95th pct)",
   "type": "timeseries",
   "description": "Время выполнения успешных запросов (95thpct)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  { "title": "Run Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Run Test",
   "type": "table",
   "description": "Таблица запущенных / завершенных тестов",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "jmeter_events{event=\"start\"}",
     "groupBy": [
      { "params": [ "tags" ], "type": "tag" },
      { "params": [ "application" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "events",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* started/" }
     ]
    },
    {
     "expr": "jmeter_events{event=\"end\"}",
     "groupBy": [
      { "params": [ "tags" ], "type": "tag" },
      { "params": [ "application" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "events",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* ended/" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Active Threads - Total Throughput",
   "type": "timeseries",
   "description": "Активные потоки / Кол-во запросов в секунду",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Threads",
     "expr": "jmeter_maxAT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "RPS",
     "expr": "jmeter_count{application=\"$application\",transaction=\"all\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "RPS",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmeter_maxAT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Finished Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmeter_endedT{application=\"$application\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "endedT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_countError{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_rb{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "jmeter_sb{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total Error",
   "type": "timeseries",
   "description": "Кол-во ошибок",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Num of Errors",
     "expr": "jmeter_countError{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Num of Errors",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "totalCount",
     "expr": "jmeter_count{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "application" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "totalReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "totalCountError",
     "expr": "jmeter_countError{application=\"$application\",transaction=\"all\"}",
     "groupBy": [
      { "params": [ "application" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "totalFail" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  { "title": "RPS / Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "RPS - Pass",
   "type": "timeseries",
   "description": "Кол-во успешных запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5",
     "legendFormat": "{{transaction}}"
    },
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"} / 5)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "RPS - Failed",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"} / 5",
     "legendFormat": "{{transaction}}"
    },
    {
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"} / 5)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Response Time - Pass (95th pct)",
   "type": "timeseries",
   "description": "Время выполнения успешных запросов (95thpct)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ok\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time - Failed (95th pct)",
   "type": "timeseries",
   "description": "Время выполнения неудачных запросов (95thpct)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_pct95.0{application=\"$application\",transaction=~\"$transaction\",statut=\"ko\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS - 4xx",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду с кодом ответа 4xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"4..\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"4..\"} / 5)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "all",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" }
     ]
    }
   ]
  },
  {
   "title": "RPS - 5xx",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду с кодом ответа 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"5..\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode=~\"5..\"} / 5)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "all",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" }
     ]
    }
   ]
  },
  {
   "title": "Total Error - Response Code",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов по кодам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode!~\"^$\"}) by (responseCode)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{responseCode}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Pie - Error Response Code",
   "type": "piechart",
   "description": "Пирог с процентом ошибок по кодам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "expr": "sum(jmeter_count{application=\"$application\",transaction=~\"$transaction\",responseCode!~\"^$\"}) by (responseCode)",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Error Info",
   "type": "table",
   "description": "Таблица с краткой информацией об ошибках",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",responseCode!~\"^$\"}",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "responseMessage" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
     ]
    }
   ]
  },
  { "title": "Transaction Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Transaction Table",
   "type": "table",
   "description": "Таблица со статистикой запросов / транзакций",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jmeter_count{application=\"$application\",statut=\"ok\",transaction!=\"all\"}",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "passReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_count{application=\"$application\",statut=\"ko\",transaction!=\"all\"}",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "failReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_pct90.0{application=\"$application\",transaction!=\"all\"}",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_pct95.0{application=\"$application\",transaction!=\"all\"}",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_pct99.0{application=\"$application\",transaction!=\"all\"}",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_count{application=\"$application\",transaction!=\"all\"} / 5",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsAvg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "expr": "jmeter_count{application=\"$application\",transaction!=\"all\"} / 5",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsMax" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "description": "Полученные байты",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_rb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "alias": "all",
     "expr": "sum(jmeter_rb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "all",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "rb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "description": "Отправленные байты",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "expr": "jmeter_sb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{transaction}}",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "alias": "all",
     "expr": "sum(jmeter_sb{application=\"$application\",transaction=~\"$transaction\",statut=\"all\"} / 5)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "all",
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  }
 ]
}