// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bank_order.proto
// Protobuf Java Version: 4.32.1

package ru.alfabank.grpc;

@com.google.protobuf.Generated
public interface BankOrderExecRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.alfabank.grpc.BankOrderExecRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operation_external_uid = 1;</code>
   * @return The operationExternalUid.
   */
  String getOperationExternalUid();
  /**
   * <code>string operation_external_uid = 1;</code>
   * @return The bytes for operationExternalUid.
   */
  com.google.protobuf.ByteString
      getOperationExternalUidBytes();

  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   * @return Whether the operationDate field is set.
   */
  boolean hasOperationDate();
  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   * @return The operationDate.
   */
  com.google.protobuf.Timestamp getOperationDate();
  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getOperationDateOrBuilder();

  /**
   * <code>uint64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>string amount_currency = 4;</code>
   * @return The amountCurrency.
   */
  String getAmountCurrency();
  /**
   * <code>string amount_currency = 4;</code>
   * @return The bytes for amountCurrency.
   */
  com.google.protobuf.ByteString
      getAmountCurrencyBytes();

  /**
   * <code>string payer_account = 5;</code>
   * @return The payerAccount.
   */
  String getPayerAccount();
  /**
   * <code>string payer_account = 5;</code>
   * @return The bytes for payerAccount.
   */
  com.google.protobuf.ByteString
      getPayerAccountBytes();

  /**
   * <code>optional string payer_name = 6;</code>
   * @return Whether the payerName field is set.
   */
  boolean hasPayerName();
  /**
   * <code>optional string payer_name = 6;</code>
   * @return The payerName.
   */
  String getPayerName();
  /**
   * <code>optional string payer_name = 6;</code>
   * @return The bytes for payerName.
   */
  com.google.protobuf.ByteString
      getPayerNameBytes();

  /**
   * <code>string payee_account = 7;</code>
   * @return The payeeAccount.
   */
  String getPayeeAccount();
  /**
   * <code>string payee_account = 7;</code>
   * @return The bytes for payeeAccount.
   */
  com.google.protobuf.ByteString
      getPayeeAccountBytes();

  /**
   * <code>optional string payee_name = 8;</code>
   * @return Whether the payeeName field is set.
   */
  boolean hasPayeeName();
  /**
   * <code>optional string payee_name = 8;</code>
   * @return The payeeName.
   */
  String getPayeeName();
  /**
   * <code>optional string payee_name = 8;</code>
   * @return The bytes for payeeName.
   */
  com.google.protobuf.ByteString
      getPayeeNameBytes();

  /**
   * <code>string payment_purpose = 9;</code>
   * @return The paymentPurpose.
   */
  String getPaymentPurpose();
  /**
   * <code>string payment_purpose = 9;</code>
   * @return The bytes for paymentPurpose.
   */
  com.google.protobuf.ByteString
      getPaymentPurposeBytes();

  /**
   * <code>uint32 payment_priority = 10;</code>
   * @return The paymentPriority.
   */
  int getPaymentPriority();
}
