// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bank_order.proto
// Protobuf Java Version: 4.32.1

package ru.alfabank.grpc;

@com.google.protobuf.Generated
public final class BankOrderProto extends com.google.protobuf.GeneratedFile {
  private BankOrderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BankOrderProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_alfabank_grpc_BankOrderExecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_alfabank_grpc_BankOrderExecResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020bank_order.proto\022\020ru.alfabank.grpc\032\037go" +
      "ogle/protobuf/timestamp.proto\"\304\002\n\024BankOr" +
      "derExecRequest\022\036\n\026operation_external_uid" +
      "\030\001 \001(\t\0222\n\016operation_date\030\002 \001(\0132\032.google." +
      "protobuf.Timestamp\022\016\n\006amount\030\003 \001(\004\022\027\n\017am" +
      "ount_currency\030\004 \001(\t\022\025\n\rpayer_account\030\005 \001" +
      "(\t\022\027\n\npayer_name\030\006 \001(\tH\000\210\001\001\022\025\n\rpayee_acc" +
      "ount\030\007 \001(\t\022\027\n\npayee_name\030\010 \001(\tH\001\210\001\001\022\027\n\017p" +
      "ayment_purpose\030\t \001(\t\022\030\n\020payment_priority" +
      "\030\n \001(\rB\r\n\013_payer_nameB\r\n\013_payee_name\"\350\002\n" +
      "\025BankOrderExecResponse\022Q\n\020operation_stat" +
      "us\030\001 \001(\01627.ru.alfabank.grpc.BankOrderExe" +
      "cResponse.OperationStatus\022\034\n\017operation_e" +
      "rror\030\002 \001(\tH\000\210\001\001\022$\n\027operation_error_messa" +
      "ge\030\003 \001(\tH\001\210\001\001\"\207\001\n\017OperationStatus\022\032\n\026OPE" +
      "RATION_STATUS_DRAFT\020\000\022\035\n\031OPERATION_STATU" +
      "S_EXECUTED\020\001\022\035\n\031OPERATION_STATUS_DECLINE" +
      "D\020\002\022\032\n\026OPERATION_STATUS_ERROR\020\003B\022\n\020_oper" +
      "ation_errorB\032\n\030_operation_error_message2" +
      "~\n\032SettlementOperationService\022`\n\rExecBan" +
      "kOrder\022&.ru.alfabank.grpc.BankOrderExecR" +
      "equest\032\'.ru.alfabank.grpc.BankOrderExecR" +
      "esponseB$\n\020ru.alfabank.grpcB\016BankOrderPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_alfabank_grpc_BankOrderExecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor,
        new String[] { "OperationExternalUid", "OperationDate", "Amount", "AmountCurrency", "PayerAccount", "PayerName", "PayeeAccount", "PayeeName", "PaymentPurpose", "PaymentPriority", });
    internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_alfabank_grpc_BankOrderExecResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor,
        new String[] { "OperationStatus", "OperationError", "OperationErrorMessage", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
