// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bank_order.proto
// Protobuf Java Version: 4.32.1

package ru.alfabank.grpc;

/**
 * Protobuf type {@code ru.alfabank.grpc.BankOrderExecResponse}
 */
@com.google.protobuf.Generated
public final class BankOrderExecResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ru.alfabank.grpc.BankOrderExecResponse)
    BankOrderExecResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BankOrderExecResponse.class.getName());
  }
  // Use BankOrderExecResponse.newBuilder() to construct.
  private BankOrderExecResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BankOrderExecResponse() {
    operationStatus_ = 0;
    operationError_ = "";
    operationErrorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BankOrderExecResponse.class, Builder.class);
  }

  /**
   * Protobuf enum {@code ru.alfabank.grpc.BankOrderExecResponse.OperationStatus}
   */
  public enum OperationStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OPERATION_STATUS_DRAFT = 0;</code>
     */
    OPERATION_STATUS_DRAFT(0),
    /**
     * <code>OPERATION_STATUS_EXECUTED = 1;</code>
     */
    OPERATION_STATUS_EXECUTED(1),
    /**
     * <code>OPERATION_STATUS_DECLINED = 2;</code>
     */
    OPERATION_STATUS_DECLINED(2),
    /**
     * <code>OPERATION_STATUS_ERROR = 3;</code>
     */
    OPERATION_STATUS_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        OperationStatus.class.getName());
    }
    /**
     * <code>OPERATION_STATUS_DRAFT = 0;</code>
     */
    public static final int OPERATION_STATUS_DRAFT_VALUE = 0;
    /**
     * <code>OPERATION_STATUS_EXECUTED = 1;</code>
     */
    public static final int OPERATION_STATUS_EXECUTED_VALUE = 1;
    /**
     * <code>OPERATION_STATUS_DECLINED = 2;</code>
     */
    public static final int OPERATION_STATUS_DECLINED_VALUE = 2;
    /**
     * <code>OPERATION_STATUS_ERROR = 3;</code>
     */
    public static final int OPERATION_STATUS_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperationStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OperationStatus forNumber(int value) {
      switch (value) {
        case 0: return OPERATION_STATUS_DRAFT;
        case 1: return OPERATION_STATUS_EXECUTED;
        case 2: return OPERATION_STATUS_DECLINED;
        case 3: return OPERATION_STATUS_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationStatus>() {
            public OperationStatus findValueByNumber(int number) {
              return OperationStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BankOrderExecResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationStatus[] VALUES = values();

    public static OperationStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ru.alfabank.grpc.BankOrderExecResponse.OperationStatus)
  }

  private int bitField0_;
  public static final int OPERATION_STATUS_FIELD_NUMBER = 1;
  private int operationStatus_ = 0;
  /**
   * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
   * @return The enum numeric value on the wire for operationStatus.
   */
  @Override public int getOperationStatusValue() {
    return operationStatus_;
  }
  /**
   * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
   * @return The operationStatus.
   */
  @Override public OperationStatus getOperationStatus() {
    OperationStatus result = OperationStatus.forNumber(operationStatus_);
    return result == null ? OperationStatus.UNRECOGNIZED : result;
  }

  public static final int OPERATION_ERROR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object operationError_ = "";
  /**
   * <code>optional string operation_error = 2;</code>
   * @return Whether the operationError field is set.
   */
  @Override
  public boolean hasOperationError() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string operation_error = 2;</code>
   * @return The operationError.
   */
  @Override
  public String getOperationError() {
    Object ref = operationError_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      operationError_ = s;
      return s;
    }
  }
  /**
   * <code>optional string operation_error = 2;</code>
   * @return The bytes for operationError.
   */
  @Override
  public com.google.protobuf.ByteString
      getOperationErrorBytes() {
    Object ref = operationError_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      operationError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_ERROR_MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object operationErrorMessage_ = "";
  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return Whether the operationErrorMessage field is set.
   */
  @Override
  public boolean hasOperationErrorMessage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return The operationErrorMessage.
   */
  @Override
  public String getOperationErrorMessage() {
    Object ref = operationErrorMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      operationErrorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return The bytes for operationErrorMessage.
   */
  @Override
  public com.google.protobuf.ByteString
      getOperationErrorMessageBytes() {
    Object ref = operationErrorMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      operationErrorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operationStatus_ != OperationStatus.OPERATION_STATUS_DRAFT.getNumber()) {
      output.writeEnum(1, operationStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, operationError_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, operationErrorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (operationStatus_ != OperationStatus.OPERATION_STATUS_DRAFT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, operationStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, operationError_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, operationErrorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BankOrderExecResponse)) {
      return super.equals(obj);
    }
    BankOrderExecResponse other = (BankOrderExecResponse) obj;

    if (operationStatus_ != other.operationStatus_) return false;
    if (hasOperationError() != other.hasOperationError()) return false;
    if (hasOperationError()) {
      if (!getOperationError()
          .equals(other.getOperationError())) return false;
    }
    if (hasOperationErrorMessage() != other.hasOperationErrorMessage()) return false;
    if (hasOperationErrorMessage()) {
      if (!getOperationErrorMessage()
          .equals(other.getOperationErrorMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + operationStatus_;
    if (hasOperationError()) {
      hash = (37 * hash) + OPERATION_ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getOperationError().hashCode();
    }
    if (hasOperationErrorMessage()) {
      hash = (37 * hash) + OPERATION_ERROR_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationErrorMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BankOrderExecResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BankOrderExecResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BankOrderExecResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BankOrderExecResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BankOrderExecResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BankOrderExecResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BankOrderExecResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.alfabank.grpc.BankOrderExecResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.alfabank.grpc.BankOrderExecResponse)
      BankOrderExecResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BankOrderExecResponse.class, Builder.class);
    }

    // Construct using ru.alfabank.grpc.BankOrderExecResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      operationStatus_ = 0;
      operationError_ = "";
      operationErrorMessage_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecResponse_descriptor;
    }

    @Override
    public BankOrderExecResponse getDefaultInstanceForType() {
      return BankOrderExecResponse.getDefaultInstance();
    }

    @Override
    public BankOrderExecResponse build() {
      BankOrderExecResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BankOrderExecResponse buildPartial() {
      BankOrderExecResponse result = new BankOrderExecResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BankOrderExecResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.operationStatus_ = operationStatus_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.operationError_ = operationError_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.operationErrorMessage_ = operationErrorMessage_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BankOrderExecResponse) {
        return mergeFrom((BankOrderExecResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BankOrderExecResponse other) {
      if (other == BankOrderExecResponse.getDefaultInstance()) return this;
      if (other.operationStatus_ != 0) {
        setOperationStatusValue(other.getOperationStatusValue());
      }
      if (other.hasOperationError()) {
        operationError_ = other.operationError_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasOperationErrorMessage()) {
        operationErrorMessage_ = other.operationErrorMessage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              operationStatus_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              operationError_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              operationErrorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int operationStatus_ = 0;
    /**
     * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
     * @return The enum numeric value on the wire for operationStatus.
     */
    @Override public int getOperationStatusValue() {
      return operationStatus_;
    }
    /**
     * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
     * @param value The enum numeric value on the wire for operationStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOperationStatusValue(int value) {
      operationStatus_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
     * @return The operationStatus.
     */
    @Override
    public OperationStatus getOperationStatus() {
      OperationStatus result = OperationStatus.forNumber(operationStatus_);
      return result == null ? OperationStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
     * @param value The operationStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOperationStatus(OperationStatus value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      operationStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      operationStatus_ = 0;
      onChanged();
      return this;
    }

    private Object operationError_ = "";
    /**
     * <code>optional string operation_error = 2;</code>
     * @return Whether the operationError field is set.
     */
    public boolean hasOperationError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string operation_error = 2;</code>
     * @return The operationError.
     */
    public String getOperationError() {
      Object ref = operationError_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationError_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string operation_error = 2;</code>
     * @return The bytes for operationError.
     */
    public com.google.protobuf.ByteString
        getOperationErrorBytes() {
      Object ref = operationError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string operation_error = 2;</code>
     * @param value The operationError to set.
     * @return This builder for chaining.
     */
    public Builder setOperationError(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      operationError_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string operation_error = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationError() {
      operationError_ = getDefaultInstance().getOperationError();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string operation_error = 2;</code>
     * @param value The bytes for operationError to set.
     * @return This builder for chaining.
     */
    public Builder setOperationErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operationError_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object operationErrorMessage_ = "";
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @return Whether the operationErrorMessage field is set.
     */
    public boolean hasOperationErrorMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @return The operationErrorMessage.
     */
    public String getOperationErrorMessage() {
      Object ref = operationErrorMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationErrorMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @return The bytes for operationErrorMessage.
     */
    public com.google.protobuf.ByteString
        getOperationErrorMessageBytes() {
      Object ref = operationErrorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationErrorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @param value The operationErrorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setOperationErrorMessage(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      operationErrorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationErrorMessage() {
      operationErrorMessage_ = getDefaultInstance().getOperationErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string operation_error_message = 3;</code>
     * @param value The bytes for operationErrorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setOperationErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operationErrorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ru.alfabank.grpc.BankOrderExecResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.alfabank.grpc.BankOrderExecResponse)
  private static final BankOrderExecResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BankOrderExecResponse();
  }

  public static BankOrderExecResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BankOrderExecResponse>
      PARSER = new com.google.protobuf.AbstractParser<BankOrderExecResponse>() {
    @Override
    public BankOrderExecResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BankOrderExecResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BankOrderExecResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public BankOrderExecResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

