// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bank_order.proto
// Protobuf Java Version: 4.32.1

package ru.alfabank.grpc;

/**
 * Protobuf type {@code ru.alfabank.grpc.BankOrderExecRequest}
 */
@com.google.protobuf.Generated
public final class BankOrderExecRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ru.alfabank.grpc.BankOrderExecRequest)
    BankOrderExecRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BankOrderExecRequest.class.getName());
  }
  // Use BankOrderExecRequest.newBuilder() to construct.
  private BankOrderExecRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BankOrderExecRequest() {
    operationExternalUid_ = "";
    amountCurrency_ = "";
    payerAccount_ = "";
    payerName_ = "";
    payeeAccount_ = "";
    payeeName_ = "";
    paymentPurpose_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BankOrderExecRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int OPERATION_EXTERNAL_UID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object operationExternalUid_ = "";
  /**
   * <code>string operation_external_uid = 1;</code>
   * @return The operationExternalUid.
   */
  @Override
  public String getOperationExternalUid() {
    Object ref = operationExternalUid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      operationExternalUid_ = s;
      return s;
    }
  }
  /**
   * <code>string operation_external_uid = 1;</code>
   * @return The bytes for operationExternalUid.
   */
  @Override
  public com.google.protobuf.ByteString
      getOperationExternalUidBytes() {
    Object ref = operationExternalUid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      operationExternalUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_DATE_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp operationDate_;
  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   * @return Whether the operationDate field is set.
   */
  @Override
  public boolean hasOperationDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   * @return The operationDate.
   */
  @Override
  public com.google.protobuf.Timestamp getOperationDate() {
    return operationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : operationDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp operation_date = 2;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getOperationDateOrBuilder() {
    return operationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : operationDate_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private long amount_ = 0L;
  /**
   * <code>uint64 amount = 3;</code>
   * @return The amount.
   */
  @Override
  public long getAmount() {
    return amount_;
  }

  public static final int AMOUNT_CURRENCY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object amountCurrency_ = "";
  /**
   * <code>string amount_currency = 4;</code>
   * @return The amountCurrency.
   */
  @Override
  public String getAmountCurrency() {
    Object ref = amountCurrency_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      amountCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string amount_currency = 4;</code>
   * @return The bytes for amountCurrency.
   */
  @Override
  public com.google.protobuf.ByteString
      getAmountCurrencyBytes() {
    Object ref = amountCurrency_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      amountCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYER_ACCOUNT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object payerAccount_ = "";
  /**
   * <code>string payer_account = 5;</code>
   * @return The payerAccount.
   */
  @Override
  public String getPayerAccount() {
    Object ref = payerAccount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      payerAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string payer_account = 5;</code>
   * @return The bytes for payerAccount.
   */
  @Override
  public com.google.protobuf.ByteString
      getPayerAccountBytes() {
    Object ref = payerAccount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      payerAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYER_NAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object payerName_ = "";
  /**
   * <code>optional string payer_name = 6;</code>
   * @return Whether the payerName field is set.
   */
  @Override
  public boolean hasPayerName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string payer_name = 6;</code>
   * @return The payerName.
   */
  @Override
  public String getPayerName() {
    Object ref = payerName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      payerName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string payer_name = 6;</code>
   * @return The bytes for payerName.
   */
  @Override
  public com.google.protobuf.ByteString
      getPayerNameBytes() {
    Object ref = payerName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      payerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYEE_ACCOUNT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object payeeAccount_ = "";
  /**
   * <code>string payee_account = 7;</code>
   * @return The payeeAccount.
   */
  @Override
  public String getPayeeAccount() {
    Object ref = payeeAccount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      payeeAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string payee_account = 7;</code>
   * @return The bytes for payeeAccount.
   */
  @Override
  public com.google.protobuf.ByteString
      getPayeeAccountBytes() {
    Object ref = payeeAccount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      payeeAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYEE_NAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object payeeName_ = "";
  /**
   * <code>optional string payee_name = 8;</code>
   * @return Whether the payeeName field is set.
   */
  @Override
  public boolean hasPayeeName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string payee_name = 8;</code>
   * @return The payeeName.
   */
  @Override
  public String getPayeeName() {
    Object ref = payeeName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      payeeName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string payee_name = 8;</code>
   * @return The bytes for payeeName.
   */
  @Override
  public com.google.protobuf.ByteString
      getPayeeNameBytes() {
    Object ref = payeeName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      payeeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYMENT_PURPOSE_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile Object paymentPurpose_ = "";
  /**
   * <code>string payment_purpose = 9;</code>
   * @return The paymentPurpose.
   */
  @Override
  public String getPaymentPurpose() {
    Object ref = paymentPurpose_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      paymentPurpose_ = s;
      return s;
    }
  }
  /**
   * <code>string payment_purpose = 9;</code>
   * @return The bytes for paymentPurpose.
   */
  @Override
  public com.google.protobuf.ByteString
      getPaymentPurposeBytes() {
    Object ref = paymentPurpose_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      paymentPurpose_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYMENT_PRIORITY_FIELD_NUMBER = 10;
  private int paymentPriority_ = 0;
  /**
   * <code>uint32 payment_priority = 10;</code>
   * @return The paymentPriority.
   */
  @Override
  public int getPaymentPriority() {
    return paymentPriority_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operationExternalUid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, operationExternalUid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getOperationDate());
    }
    if (amount_ != 0L) {
      output.writeUInt64(3, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amountCurrency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, amountCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payerAccount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, payerAccount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, payerName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payeeAccount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, payeeAccount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, payeeName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(paymentPurpose_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, paymentPurpose_);
    }
    if (paymentPriority_ != 0) {
      output.writeUInt32(10, paymentPriority_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operationExternalUid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, operationExternalUid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOperationDate());
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, amount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(amountCurrency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, amountCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payerAccount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, payerAccount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, payerName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payeeAccount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, payeeAccount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, payeeName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(paymentPurpose_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, paymentPurpose_);
    }
    if (paymentPriority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, paymentPriority_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BankOrderExecRequest)) {
      return super.equals(obj);
    }
    BankOrderExecRequest other = (BankOrderExecRequest) obj;

    if (!getOperationExternalUid()
        .equals(other.getOperationExternalUid())) return false;
    if (hasOperationDate() != other.hasOperationDate()) return false;
    if (hasOperationDate()) {
      if (!getOperationDate()
          .equals(other.getOperationDate())) return false;
    }
    if (getAmount()
        != other.getAmount()) return false;
    if (!getAmountCurrency()
        .equals(other.getAmountCurrency())) return false;
    if (!getPayerAccount()
        .equals(other.getPayerAccount())) return false;
    if (hasPayerName() != other.hasPayerName()) return false;
    if (hasPayerName()) {
      if (!getPayerName()
          .equals(other.getPayerName())) return false;
    }
    if (!getPayeeAccount()
        .equals(other.getPayeeAccount())) return false;
    if (hasPayeeName() != other.hasPayeeName()) return false;
    if (hasPayeeName()) {
      if (!getPayeeName()
          .equals(other.getPayeeName())) return false;
    }
    if (!getPaymentPurpose()
        .equals(other.getPaymentPurpose())) return false;
    if (getPaymentPriority()
        != other.getPaymentPriority()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_EXTERNAL_UID_FIELD_NUMBER;
    hash = (53 * hash) + getOperationExternalUid().hashCode();
    if (hasOperationDate()) {
      hash = (37 * hash) + OPERATION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationDate().hashCode();
    }
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + AMOUNT_CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getAmountCurrency().hashCode();
    hash = (37 * hash) + PAYER_ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPayerAccount().hashCode();
    if (hasPayerName()) {
      hash = (37 * hash) + PAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPayerName().hashCode();
    }
    hash = (37 * hash) + PAYEE_ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPayeeAccount().hashCode();
    if (hasPayeeName()) {
      hash = (37 * hash) + PAYEE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPayeeName().hashCode();
    }
    hash = (37 * hash) + PAYMENT_PURPOSE_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentPurpose().hashCode();
    hash = (37 * hash) + PAYMENT_PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentPriority();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BankOrderExecRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BankOrderExecRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BankOrderExecRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BankOrderExecRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BankOrderExecRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BankOrderExecRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BankOrderExecRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BankOrderExecRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BankOrderExecRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.alfabank.grpc.BankOrderExecRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.alfabank.grpc.BankOrderExecRequest)
      BankOrderExecRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BankOrderExecRequest.class, Builder.class);
    }

    // Construct using ru.alfabank.grpc.BankOrderExecRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetOperationDateFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      operationExternalUid_ = "";
      operationDate_ = null;
      if (operationDateBuilder_ != null) {
        operationDateBuilder_.dispose();
        operationDateBuilder_ = null;
      }
      amount_ = 0L;
      amountCurrency_ = "";
      payerAccount_ = "";
      payerName_ = "";
      payeeAccount_ = "";
      payeeName_ = "";
      paymentPurpose_ = "";
      paymentPriority_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BankOrderProto.internal_static_ru_alfabank_grpc_BankOrderExecRequest_descriptor;
    }

    @Override
    public BankOrderExecRequest getDefaultInstanceForType() {
      return BankOrderExecRequest.getDefaultInstance();
    }

    @Override
    public BankOrderExecRequest build() {
      BankOrderExecRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BankOrderExecRequest buildPartial() {
      BankOrderExecRequest result = new BankOrderExecRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BankOrderExecRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.operationExternalUid_ = operationExternalUid_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.operationDate_ = operationDateBuilder_ == null
            ? operationDate_
            : operationDateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.amountCurrency_ = amountCurrency_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.payerAccount_ = payerAccount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.payerName_ = payerName_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.payeeAccount_ = payeeAccount_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.payeeName_ = payeeName_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.paymentPurpose_ = paymentPurpose_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.paymentPriority_ = paymentPriority_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BankOrderExecRequest) {
        return mergeFrom((BankOrderExecRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BankOrderExecRequest other) {
      if (other == BankOrderExecRequest.getDefaultInstance()) return this;
      if (!other.getOperationExternalUid().isEmpty()) {
        operationExternalUid_ = other.operationExternalUid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOperationDate()) {
        mergeOperationDate(other.getOperationDate());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getAmountCurrency().isEmpty()) {
        amountCurrency_ = other.amountCurrency_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPayerAccount().isEmpty()) {
        payerAccount_ = other.payerAccount_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasPayerName()) {
        payerName_ = other.payerName_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getPayeeAccount().isEmpty()) {
        payeeAccount_ = other.payeeAccount_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasPayeeName()) {
        payeeName_ = other.payeeName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getPaymentPurpose().isEmpty()) {
        paymentPurpose_ = other.paymentPurpose_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getPaymentPriority() != 0) {
        setPaymentPriority(other.getPaymentPriority());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              operationExternalUid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetOperationDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              amount_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              amountCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              payerAccount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              payerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              payeeAccount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              payeeName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              paymentPurpose_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              paymentPriority_ = input.readUInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object operationExternalUid_ = "";
    /**
     * <code>string operation_external_uid = 1;</code>
     * @return The operationExternalUid.
     */
    public String getOperationExternalUid() {
      Object ref = operationExternalUid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationExternalUid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string operation_external_uid = 1;</code>
     * @return The bytes for operationExternalUid.
     */
    public com.google.protobuf.ByteString
        getOperationExternalUidBytes() {
      Object ref = operationExternalUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationExternalUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operation_external_uid = 1;</code>
     * @param value The operationExternalUid to set.
     * @return This builder for chaining.
     */
    public Builder setOperationExternalUid(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      operationExternalUid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string operation_external_uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationExternalUid() {
      operationExternalUid_ = getDefaultInstance().getOperationExternalUid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string operation_external_uid = 1;</code>
     * @param value The bytes for operationExternalUid to set.
     * @return This builder for chaining.
     */
    public Builder setOperationExternalUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operationExternalUid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp operationDate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> operationDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     * @return Whether the operationDate field is set.
     */
    public boolean hasOperationDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     * @return The operationDate.
     */
    public com.google.protobuf.Timestamp getOperationDate() {
      if (operationDateBuilder_ == null) {
        return operationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : operationDate_;
      } else {
        return operationDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public Builder setOperationDate(com.google.protobuf.Timestamp value) {
      if (operationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operationDate_ = value;
      } else {
        operationDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public Builder setOperationDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (operationDateBuilder_ == null) {
        operationDate_ = builderForValue.build();
      } else {
        operationDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public Builder mergeOperationDate(com.google.protobuf.Timestamp value) {
      if (operationDateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          operationDate_ != null &&
          operationDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getOperationDateBuilder().mergeFrom(value);
        } else {
          operationDate_ = value;
        }
      } else {
        operationDateBuilder_.mergeFrom(value);
      }
      if (operationDate_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public Builder clearOperationDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operationDate_ = null;
      if (operationDateBuilder_ != null) {
        operationDateBuilder_.dispose();
        operationDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getOperationDateBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetOperationDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOperationDateOrBuilder() {
      if (operationDateBuilder_ != null) {
        return operationDateBuilder_.getMessageOrBuilder();
      } else {
        return operationDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : operationDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp operation_date = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetOperationDateFieldBuilder() {
      if (operationDateBuilder_ == null) {
        operationDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getOperationDate(),
                getParentForChildren(),
                isClean());
        operationDate_ = null;
      }
      return operationDateBuilder_;
    }

    private long amount_ ;
    /**
     * <code>uint64 amount = 3;</code>
     * @return The amount.
     */
    @Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>uint64 amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private Object amountCurrency_ = "";
    /**
     * <code>string amount_currency = 4;</code>
     * @return The amountCurrency.
     */
    public String getAmountCurrency() {
      Object ref = amountCurrency_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        amountCurrency_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string amount_currency = 4;</code>
     * @return The bytes for amountCurrency.
     */
    public com.google.protobuf.ByteString
        getAmountCurrencyBytes() {
      Object ref = amountCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        amountCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string amount_currency = 4;</code>
     * @param value The amountCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setAmountCurrency(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      amountCurrency_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string amount_currency = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountCurrency() {
      amountCurrency_ = getDefaultInstance().getAmountCurrency();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string amount_currency = 4;</code>
     * @param value The bytes for amountCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setAmountCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      amountCurrency_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object payerAccount_ = "";
    /**
     * <code>string payer_account = 5;</code>
     * @return The payerAccount.
     */
    public String getPayerAccount() {
      Object ref = payerAccount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payerAccount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string payer_account = 5;</code>
     * @return The bytes for payerAccount.
     */
    public com.google.protobuf.ByteString
        getPayerAccountBytes() {
      Object ref = payerAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payerAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payer_account = 5;</code>
     * @param value The payerAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPayerAccount(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      payerAccount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string payer_account = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayerAccount() {
      payerAccount_ = getDefaultInstance().getPayerAccount();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string payer_account = 5;</code>
     * @param value The bytes for payerAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPayerAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payerAccount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object payerName_ = "";
    /**
     * <code>optional string payer_name = 6;</code>
     * @return Whether the payerName field is set.
     */
    public boolean hasPayerName() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string payer_name = 6;</code>
     * @return The payerName.
     */
    public String getPayerName() {
      Object ref = payerName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payerName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string payer_name = 6;</code>
     * @return The bytes for payerName.
     */
    public com.google.protobuf.ByteString
        getPayerNameBytes() {
      Object ref = payerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string payer_name = 6;</code>
     * @param value The payerName to set.
     * @return This builder for chaining.
     */
    public Builder setPayerName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      payerName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string payer_name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayerName() {
      payerName_ = getDefaultInstance().getPayerName();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string payer_name = 6;</code>
     * @param value The bytes for payerName to set.
     * @return This builder for chaining.
     */
    public Builder setPayerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payerName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object payeeAccount_ = "";
    /**
     * <code>string payee_account = 7;</code>
     * @return The payeeAccount.
     */
    public String getPayeeAccount() {
      Object ref = payeeAccount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payeeAccount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string payee_account = 7;</code>
     * @return The bytes for payeeAccount.
     */
    public com.google.protobuf.ByteString
        getPayeeAccountBytes() {
      Object ref = payeeAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payeeAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payee_account = 7;</code>
     * @param value The payeeAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPayeeAccount(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      payeeAccount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string payee_account = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayeeAccount() {
      payeeAccount_ = getDefaultInstance().getPayeeAccount();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string payee_account = 7;</code>
     * @param value The bytes for payeeAccount to set.
     * @return This builder for chaining.
     */
    public Builder setPayeeAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payeeAccount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object payeeName_ = "";
    /**
     * <code>optional string payee_name = 8;</code>
     * @return Whether the payeeName field is set.
     */
    public boolean hasPayeeName() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string payee_name = 8;</code>
     * @return The payeeName.
     */
    public String getPayeeName() {
      Object ref = payeeName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payeeName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string payee_name = 8;</code>
     * @return The bytes for payeeName.
     */
    public com.google.protobuf.ByteString
        getPayeeNameBytes() {
      Object ref = payeeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string payee_name = 8;</code>
     * @param value The payeeName to set.
     * @return This builder for chaining.
     */
    public Builder setPayeeName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      payeeName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional string payee_name = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayeeName() {
      payeeName_ = getDefaultInstance().getPayeeName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>optional string payee_name = 8;</code>
     * @param value The bytes for payeeName to set.
     * @return This builder for chaining.
     */
    public Builder setPayeeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payeeName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private Object paymentPurpose_ = "";
    /**
     * <code>string payment_purpose = 9;</code>
     * @return The paymentPurpose.
     */
    public String getPaymentPurpose() {
      Object ref = paymentPurpose_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paymentPurpose_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string payment_purpose = 9;</code>
     * @return The bytes for paymentPurpose.
     */
    public com.google.protobuf.ByteString
        getPaymentPurposeBytes() {
      Object ref = paymentPurpose_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paymentPurpose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payment_purpose = 9;</code>
     * @param value The paymentPurpose to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentPurpose(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      paymentPurpose_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string payment_purpose = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentPurpose() {
      paymentPurpose_ = getDefaultInstance().getPaymentPurpose();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string payment_purpose = 9;</code>
     * @param value The bytes for paymentPurpose to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentPurposeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      paymentPurpose_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private int paymentPriority_ ;
    /**
     * <code>uint32 payment_priority = 10;</code>
     * @return The paymentPriority.
     */
    @Override
    public int getPaymentPriority() {
      return paymentPriority_;
    }
    /**
     * <code>uint32 payment_priority = 10;</code>
     * @param value The paymentPriority to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentPriority(int value) {

      paymentPriority_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 payment_priority = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentPriority() {
      bitField0_ = (bitField0_ & ~0x00000200);
      paymentPriority_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ru.alfabank.grpc.BankOrderExecRequest)
  }

  // @@protoc_insertion_point(class_scope:ru.alfabank.grpc.BankOrderExecRequest)
  private static final BankOrderExecRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BankOrderExecRequest();
  }

  public static BankOrderExecRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BankOrderExecRequest>
      PARSER = new com.google.protobuf.AbstractParser<BankOrderExecRequest>() {
    @Override
    public BankOrderExecRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BankOrderExecRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BankOrderExecRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public BankOrderExecRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

