// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bank_order.proto
// Protobuf Java Version: 4.32.1

package ru.alfabank.grpc;

@com.google.protobuf.Generated
public interface BankOrderExecResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.alfabank.grpc.BankOrderExecResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
   * @return The enum numeric value on the wire for operationStatus.
   */
  int getOperationStatusValue();
  /**
   * <code>.ru.alfabank.grpc.BankOrderExecResponse.OperationStatus operation_status = 1;</code>
   * @return The operationStatus.
   */
  BankOrderExecResponse.OperationStatus getOperationStatus();

  /**
   * <code>optional string operation_error = 2;</code>
   * @return Whether the operationError field is set.
   */
  boolean hasOperationError();
  /**
   * <code>optional string operation_error = 2;</code>
   * @return The operationError.
   */
  String getOperationError();
  /**
   * <code>optional string operation_error = 2;</code>
   * @return The bytes for operationError.
   */
  com.google.protobuf.ByteString
      getOperationErrorBytes();

  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return Whether the operationErrorMessage field is set.
   */
  boolean hasOperationErrorMessage();
  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return The operationErrorMessage.
   */
  String getOperationErrorMessage();
  /**
   * <code>optional string operation_error_message = 3;</code>
   * @return The bytes for operationErrorMessage.
   */
  com.google.protobuf.ByteString
      getOperationErrorMessageBytes();
}
