// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: absrnd_mvp.proto
// Protobuf Java Version: 4.31.1

package absrnd_mvp;

@com.google.protobuf.Generated
public final class AbsrndMvp {
  private AbsrndMvp() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AbsrndMvp.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Направление движения средста
   * </pre>
   *
   * Protobuf enum {@code absrnd_mvp.FundsDirection}
   */
  public enum FundsDirection
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FUNDS_DIRECTION_DEBIT = 0;</code>
     */
    FUNDS_DIRECTION_DEBIT(0),
    /**
     * <code>FUNDS_DIRECTION_CREDIT = 1;</code>
     */
    FUNDS_DIRECTION_CREDIT(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        FundsDirection.class.getName());
    }
    /**
     * <code>FUNDS_DIRECTION_DEBIT = 0;</code>
     */
    public static final int FUNDS_DIRECTION_DEBIT_VALUE = 0;
    /**
     * <code>FUNDS_DIRECTION_CREDIT = 1;</code>
     */
    public static final int FUNDS_DIRECTION_CREDIT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FundsDirection valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FundsDirection forNumber(int value) {
      switch (value) {
        case 0: return FUNDS_DIRECTION_DEBIT;
        case 1: return FUNDS_DIRECTION_CREDIT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FundsDirection>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FundsDirection> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FundsDirection>() {
            public FundsDirection findValueByNumber(int number) {
              return FundsDirection.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return absrnd_mvp.AbsrndMvp.getDescriptor().getEnumTypes().get(0);
    }

    private static final FundsDirection[] VALUES = values();

    public static FundsDirection valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FundsDirection(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:absrnd_mvp.FundsDirection)
  }

  /**
   * <pre>
   * Тип транзакции
   * </pre>
   *
   * Protobuf enum {@code absrnd_mvp.TransactionType}
   */
  public enum TransactionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRANSACTION_TYPE_POSTING = 0;</code>
     */
    TRANSACTION_TYPE_POSTING(0),
    /**
     * <code>TRANSACTION_TYPE_HOLD = 1;</code>
     */
    TRANSACTION_TYPE_HOLD(1),
    /**
     * <code>TRANSACTION_TYPE_OVERDRAFT = 2;</code>
     */
    TRANSACTION_TYPE_OVERDRAFT(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        TransactionType.class.getName());
    }
    /**
     * <code>TRANSACTION_TYPE_POSTING = 0;</code>
     */
    public static final int TRANSACTION_TYPE_POSTING_VALUE = 0;
    /**
     * <code>TRANSACTION_TYPE_HOLD = 1;</code>
     */
    public static final int TRANSACTION_TYPE_HOLD_VALUE = 1;
    /**
     * <code>TRANSACTION_TYPE_OVERDRAFT = 2;</code>
     */
    public static final int TRANSACTION_TYPE_OVERDRAFT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransactionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TransactionType forNumber(int value) {
      switch (value) {
        case 0: return TRANSACTION_TYPE_POSTING;
        case 1: return TRANSACTION_TYPE_HOLD;
        case 2: return TRANSACTION_TYPE_OVERDRAFT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransactionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransactionType>() {
            public TransactionType findValueByNumber(int number) {
              return TransactionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return absrnd_mvp.AbsrndMvp.getDescriptor().getEnumTypes().get(1);
    }

    private static final TransactionType[] VALUES = values();

    public static TransactionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransactionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:absrnd_mvp.TransactionType)
  }

  /**
   * <pre>
   * Тип действий
   * </pre>
   *
   * Protobuf enum {@code absrnd_mvp.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTION_TYPE_POST = 0;</code>
     */
    ACTION_TYPE_POST(0),
    /**
     * <code>ACTION_TYPE_POST_ROLLBACK = 1;</code>
     */
    ACTION_TYPE_POST_ROLLBACK(1),
    /**
     * <code>ACTION_TYPE_DELETE = 2;</code>
     */
    ACTION_TYPE_DELETE(2),
    /**
     * <code>ACTION_TYPE_DELETE_ROLLBACK = 3;</code>
     */
    ACTION_TYPE_DELETE_ROLLBACK(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ActionType.class.getName());
    }
    /**
     * <code>ACTION_TYPE_POST = 0;</code>
     */
    public static final int ACTION_TYPE_POST_VALUE = 0;
    /**
     * <code>ACTION_TYPE_POST_ROLLBACK = 1;</code>
     */
    public static final int ACTION_TYPE_POST_ROLLBACK_VALUE = 1;
    /**
     * <code>ACTION_TYPE_DELETE = 2;</code>
     */
    public static final int ACTION_TYPE_DELETE_VALUE = 2;
    /**
     * <code>ACTION_TYPE_DELETE_ROLLBACK = 3;</code>
     */
    public static final int ACTION_TYPE_DELETE_ROLLBACK_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return ACTION_TYPE_POST;
        case 1: return ACTION_TYPE_POST_ROLLBACK;
        case 2: return ACTION_TYPE_DELETE;
        case 3: return ACTION_TYPE_DELETE_ROLLBACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return absrnd_mvp.AbsrndMvp.getDescriptor().getEnumTypes().get(2);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:absrnd_mvp.ActionType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020absrnd_mvp.proto\022\nabsrnd_mvp*G\n\016FundsD" +
      "irection\022\031\n\025FUNDS_DIRECTION_DEBIT\020\000\022\032\n\026F" +
      "UNDS_DIRECTION_CREDIT\020\001*j\n\017TransactionTy" +
      "pe\022\034\n\030TRANSACTION_TYPE_POSTING\020\000\022\031\n\025TRAN" +
      "SACTION_TYPE_HOLD\020\001\022\036\n\032TRANSACTION_TYPE_" +
      "OVERDRAFT\020\002*z\n\nActionType\022\024\n\020ACTION_TYPE" +
      "_POST\020\000\022\035\n\031ACTION_TYPE_POST_ROLLBACK\020\001\022\026" +
      "\n\022ACTION_TYPE_DELETE\020\002\022\037\n\033ACTION_TYPE_DE" +
      "LETE_ROLLBACK\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
